version: "3.9"

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
  celery:
    build: .
    command: celery -A socialapi worker -l info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      - web
  celery-beat:
    build: .
    command: celery -A socialapi beat -l info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      - web
